// src/components/interceptor.jsx
import React, {Component} from 'react';
import {Container} from 'react-bootstrap';
import PageTitle from './page-title'
import './interceptor.css'

export default class Interceptor extends Component {
    render() {
        return (
            <Container>
                <PageTitle page_title="Click intercepted"/>
                <div className="interceptor-content">
                    <label>
                        <input type="checkbox" id="the_checkbox"/>
                        <span className="off">A checkbox waiting to be checked</span>
                    </label>
                </div>
            </Container>
        )
    }
}

// src/routes/interceptor.svelte
<style>
    .interceptor-content {
        margin: auto;
        text-align: center;
    }

    .off {
        margin-left: -20px;
        padding-left: 25px;
        /*background-color: yellow;*/
    }
</style>
<h1>Click intercepted</h1>
<div class="interceptor-content">
	<label>
		<input type="checkbox" id="the_checkbox"/>
		<span class="off">A checkbox waiting to be checked</span>
	</label>
</div>
